use_pretrained: false
data:
    dataset: "CIFAR10"
    image_size: 32
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 4

model:
    use_time_embed: False
    type: "simple"
    attn_resolutions: [16]
    block_type: "UnetBlock"
    in_channels: 3
    out_ch: 3
    dropout: 0.1
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True
    resamp_with_conv: True
    upsamp_type: None
    num_res_blocks: 2
    ch_mult: 
      - value: [1, 2, 2, 2]
        num: 10
      - value: [1, 2]
        num: 10
    ch_num:
      - value: 128
        num: 5
      - value: 64
        num: 5
      - value: 16
        num: 5
      - value: 8
        num: 5

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000
    num_block: 20
    learn_alpha: false

training:
    batch_size: 16
    n_epochs: 10000
    n_iters: 5000000
    snapshot_freq: 500
    sample_freq: 500
    fid_freq: 5000
    # use_ckpt: /home/bingwenzhang/ddim/exp/logs/2024-03-26-22-31-35/ckpt.pth
    use_true_x: true
    use_adv_loss: false
    use_loss_weight: true
    use_mean: true
    detach: false
    first_only: true

eval:
    num_images: 50000
    batch_size: 256
    fid_cache: /home/bingwenzhang/ddim/stats/cifar10.train.npz

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0002
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0
